import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import type { WorkspaceSidebarLabels } from "@/components/omnichannel/types/workspace-labels";

export function useWorkspaceSidebarLabels(): WorkspaceSidebarLabels {
  const { t } = useTranslation("common");
  return useMemo(
    () => ({
      conversation: t("omnichannel.sidebar.tabs.conversation"),
      customer: t("omnichannel.sidebar.customer"),
      overview: t("omnichannel.sidebar.overview"),
      aiSummary: t("omnichannel.sidebar.aiSummary"),
      crm: t("omnichannel.sidebar.crm"),
      assignment: t("omnichannel.sidebar.assignment"),
      properties: t("omnichannel.sidebar.properties"),
      timeline: t("omnichannel.sidebar.timeline"),
      internalNotes: t("omnichannel.sidebar.internalNotes"),
      internalNotesPanel: {
        empty: t("omnichannel.sidebar.internalNotesEmpty"),
        author: t("omnichannel.sidebar.internalNotesAuthor"),
        edit: t("omnichannel.sidebar.internalNotesEdit"),
        delete: t("omnichannel.sidebar.internalNotesDelete"),
        save: t("buttons.save"),
        cancel: t("buttons.cancel"),
        deleteConfirm: t("omnichannel.sidebar.internalNotesDeleteConfirm"),
        editedBy: t("omnichannel.sidebar.internalNotesEditedBy"),
        editedAt: t("omnichannel.sidebar.internalNotesEditedAt"),
        versionHistory: t("omnichannel.sidebar.internalNotesVersionHistory"),
        conversationScoped: t("omnichannel.sidebar.internalNotesScoped"),
      },
      recentActivity: t("omnichannel.sidebar.recentActivity"),
      empty: t("omnichannel.sidebar.empty"),
      summary: t("omnichannel.aiAssist.summary"),
      intent: t("omnichannel.aiAssist.intent"),
      sentiment: t("omnichannel.aiAssist.sentiment"),
      priority: t("omnichannel.header.priority"),
      suggestedReply: t("omnichannel.aiAssist.suggestedReply"),
      confidence: t("omnichannel.aiAssist.confidence"),
      assignTo: t("omnichannel.sidebar.assignTo"),
      currentOwner: t("omnichannel.customer.owner"),
      escalationHistory: t("omnichannel.sidebar.escalationHistory"),
      returnConversation: t("omnichannel.actions.returnConversation"),
      lifetimeValue: t("dashboard.customerWorkspace.ltv"),
      bookings: t("omnichannel.sidebar.bookings"),
      linkCustomer: t("omnichannel.customer.linkCustomer"),
      crmTabs: {
        customer: t("omnichannel.sidebar.crmTabs.customer"),
        orders: t("omnichannel.sidebar.crmTabs.orders"),
        invoices: t("omnichannel.sidebar.crmTabs.invoices"),
        tickets: t("omnichannel.sidebar.crmTabs.tickets"),
        activities: t("omnichannel.sidebar.crmTabs.activities"),
        timeline: t("omnichannel.sidebar.crmTabs.timeline"),
      },
      targetTypes: {
        user: t("omnichannel.assignment.user"),
        team: t("omnichannel.assignment.team"),
        department: t("omnichannel.assignment.department"),
        ai_employee: t("omnichannel.assignment.aiEmployee"),
        queue: t("omnichannel.assignment.queue"),
      },
      timelinePanel: {
        today: t("omnichannel.timeline.today"),
        yesterday: t("omnichannel.timeline.yesterday"),
        lastWeek: t("omnichannel.timeline.lastWeek"),
        assigned: t("omnichannel.timeline.assigned"),
        assignedToTeam: t("omnichannel.timeline.assignedToTeam"),
        assignedToQueue: t("omnichannel.timeline.assignedToQueue"),
        assignedToAi: t("omnichannel.timeline.assignedToAi"),
        tookOver: t("omnichannel.timeline.tookOver"),
        returnedToAi: t("omnichannel.timeline.returnedToAi"),
        escalated: t("omnichannel.timeline.escalated"),
        returnedFromEscalation: t("omnichannel.timeline.returnedFromEscalation"),
        cancelledEscalation: t("omnichannel.timeline.cancelledEscalation"),
        resolved: t("omnichannel.timeline.resolved"),
        closed: t("omnichannel.timeline.closed"),
        reopened: t("omnichannel.timeline.reopened"),
        internalNoteAdded: t("omnichannel.timeline.internalNoteAdded"),
        internalNoteEdited: t("omnichannel.timeline.internalNoteEdited"),
        internalNoteDeleted: t("omnichannel.timeline.internalNoteDeleted"),
        customerLinked: t("omnichannel.timeline.customerLinked"),
        statusChanged: t("omnichannel.timeline.statusChanged"),
        message: t("omnichannel.timeline.message"),
        filterAll: t("omnichannel.timeline.filters.all"),
        filterAssignments: t("omnichannel.timeline.filters.assignments"),
        filterEscalations: t("omnichannel.timeline.filters.escalations"),
        filterInternalNotes: t("omnichannel.timeline.filters.internalNotes"),
        filterAi: t("omnichannel.timeline.filters.ai"),
        filterStatusChanges: t("omnichannel.timeline.filters.statusChanges"),
        badgeAssignment: t("omnichannel.timeline.badges.assignment"),
        badgeEscalation: t("omnichannel.timeline.badges.escalation"),
        badgeInternalNote: t("omnichannel.timeline.badges.internalNote"),
        badgeAi: t("omnichannel.timeline.badges.ai"),
        badgeStatus: t("omnichannel.timeline.badges.status"),
        badgeCustomer: t("omnichannel.timeline.badges.customer"),
        badgeMessage: t("omnichannel.timeline.badges.message"),
        badgeUpdate: t("omnichannel.timeline.badges.update"),
        searchPlaceholder: t("omnichannel.timeline.searchPlaceholder"),
        empty: t("omnichannel.timeline.empty"),
        openAssignee: t("omnichannel.timeline.openAssignee"),
        openCustomer360: t("omnichannel.timeline.openCustomer360"),
      },
      historyPanel: {
        title: t("omnichannel.history.title"),
        aiAnalysisTitle: t("omnichannel.history.aiAnalysisTitle"),
        customerMood: t("omnichannel.history.customerMood"),
        whyTitle: t("omnichannel.history.whyTitle"),
        recommendedAction: t("omnichannel.history.recommendedAction"),
        healthTitle: t("omnichannel.history.healthTitle"),
        healthStatus: t("omnichannel.history.healthStatus"),
        healthSla: t("omnichannel.history.healthSla"),
        healthAvgResponse: t("omnichannel.history.healthAvgResponse"),
        healthAgentMessages: t("omnichannel.history.healthAgentMessages"),
        healthCustomerMessages: t("omnichannel.history.healthCustomerMessages"),
        healthInternalNotes: t("omnichannel.history.healthInternalNotes"),
        healthEscalations: t("omnichannel.history.healthEscalations"),
        healthTransfers: t("omnichannel.history.healthTransfers"),
        healthAiResponses: t("omnichannel.history.healthAiResponses"),
        healthHumanResponses: t("omnichannel.history.healthHumanResponses"),
        journeyTitle: t("omnichannel.history.journeyTitle"),
        summaryTitle: t("omnichannel.history.summaryTitle"),
        confidence: t("omnichannel.history.confidence"),
        searchPlaceholder: t("omnichannel.history.searchPlaceholder"),
        empty: t("omnichannel.history.empty"),
        openAssignee: t("omnichannel.history.openAssignee"),
        openCustomer360: t("omnichannel.history.openCustomer360"),
        viewEvent: t("omnichannel.history.viewEvent"),
        filterEverything: t("omnichannel.history.filters.everything"),
        filterMessages: t("omnichannel.history.filters.messages"),
        filterAssignments: t("omnichannel.history.filters.assignments"),
        filterAi: t("omnichannel.history.filters.ai"),
        filterCrm: t("omnichannel.history.filters.crm"),
        filterInvoices: t("omnichannel.history.filters.invoices"),
        filterBookings: t("omnichannel.history.filters.bookings"),
        filterEscalations: t("omnichannel.history.filters.escalations"),
        filterNotes: t("omnichannel.history.filters.notes"),
        filterTickets: t("omnichannel.history.filters.tickets"),
        filterWorkflow: t("omnichannel.history.filters.workflow"),
        filterAutomation: t("omnichannel.history.filters.automation"),
        dateToday: t("omnichannel.history.dates.today"),
        dateYesterday: t("omnichannel.history.dates.yesterday"),
        dateLast7Days: t("omnichannel.history.dates.last7Days"),
        dateLast30Days: t("omnichannel.history.dates.last30Days"),
        dateOlder: t("omnichannel.history.dates.older"),
        minutesShort: t("omnichannel.history.minutesShort"),
        conversationStarted: t("omnichannel.history.events.conversationStarted"),
        customerFirstMessage: t("omnichannel.history.events.customerFirstMessage"),
        customerMessage: t("omnichannel.history.events.customerMessage"),
        aiReplied: t("omnichannel.history.events.aiReplied"),
        agentMessage: t("omnichannel.history.events.agentMessage"),
        agentJoined: t("omnichannel.history.events.agentJoined"),
        aiSummaryGenerated: t("omnichannel.history.events.aiSummaryGenerated"),
        customerCreated: t("omnichannel.history.events.customerCreated"),
        bookingCreated: t("omnichannel.history.events.bookingCreated"),
        bookingUpdated: t("omnichannel.history.events.bookingUpdated"),
        invoiceCreated: t("omnichannel.history.events.invoiceCreated"),
        invoicePaid: t("omnichannel.history.events.invoicePaid"),
        ticketCreated: t("omnichannel.history.events.ticketCreated"),
        ticketResolved: t("omnichannel.history.events.ticketResolved"),
        queueChanged: t("omnichannel.history.events.queueChanged"),
        transfer: t("omnichannel.history.events.transfer"),
        customerLabel: t("omnichannel.history.actors.customer"),
        aiEmployeeLabel: t("omnichannel.history.actors.ai"),
        systemLabel: t("omnichannel.history.actors.system"),
        automationLabel: t("omnichannel.history.actors.automation"),
        workflowLabel: t("omnichannel.history.actors.workflow"),
        automationAction: t("omnichannel.history.events.automationAction"),
        workflowAction: t("omnichannel.history.events.workflowAction"),
        ticketClosed: t("omnichannel.history.events.ticketClosed"),
        badgeWorkflow: t("omnichannel.history.badges.workflow"),
        badgeAutomation: t("omnichannel.history.badges.automation"),
        assignment: t("omnichannel.timeline.assigned"),
        assigned: t("omnichannel.timeline.assigned"),
        assignedToTeam: t("omnichannel.timeline.assignedToTeam"),
        assignedToQueue: t("omnichannel.timeline.assignedToQueue"),
        assignedToAi: t("omnichannel.timeline.assignedToAi"),
        tookOver: t("omnichannel.timeline.tookOver"),
        returnedToAi: t("omnichannel.timeline.returnedToAi"),
        escalated: t("omnichannel.timeline.escalated"),
        returnedFromEscalation: t("omnichannel.timeline.returnedFromEscalation"),
        cancelledEscalation: t("omnichannel.timeline.cancelledEscalation"),
        resolved: t("omnichannel.timeline.resolved"),
        closed: t("omnichannel.timeline.closed"),
        reopened: t("omnichannel.timeline.reopened"),
        internalNoteAdded: t("omnichannel.timeline.internalNoteAdded"),
        internalNote: t("omnichannel.composer.internalNote"),
        customerLinked: t("omnichannel.timeline.customerLinked"),
        statusChanged: t("omnichannel.timeline.statusChanged"),
        conversationResolved: t("omnichannel.history.events.conversationResolved"),
        conversationClosed: t("omnichannel.history.events.conversationClosed"),
        conversationReopened: t("omnichannel.history.events.conversationReopened"),
        returnEscalation: t("omnichannel.history.events.returnEscalation"),
        badgeAssignment: t("omnichannel.history.badges.assignment"),
        badgeQueue: t("omnichannel.history.badges.queue"),
        badgeNote: t("omnichannel.history.badges.note"),
        badgeAi: t("omnichannel.history.badges.ai"),
        badgeCustomer: t("omnichannel.history.badges.customer"),
        badgeBooking: t("omnichannel.history.badges.booking"),
        badgeInvoice: t("omnichannel.history.badges.invoice"),
        badgeTicket: t("omnichannel.history.badges.ticket"),
        badgeStatus: t("omnichannel.history.badges.status"),
        badgeMessage: t("omnichannel.history.badges.message"),
        moodHappy: t("omnichannel.history.moods.happy"),
        moodSatisfied: t("omnichannel.history.moods.satisfied"),
        moodNeutral: t("omnichannel.history.moods.neutral"),
        moodConfused: t("omnichannel.history.moods.confused"),
        moodFrustrated: t("omnichannel.history.moods.frustrated"),
        moodAngry: t("omnichannel.history.moods.angry"),
        moodVeryAngry: t("omnichannel.history.moods.veryAngry"),
        moodEscalationRisk: t("omnichannel.history.moods.escalationRisk"),
        moodRefundRisk: t("omnichannel.history.moods.refundRisk"),
        moodChurnRisk: t("omnichannel.history.moods.churnRisk"),
        moodVip: t("omnichannel.history.moods.vip"),
        moodHighPurchaseIntent: t("omnichannel.history.moods.highPurchaseIntent"),
        whyRepeatedQuestion: t("omnichannel.history.why.repeatedQuestion"),
        whyNegativeWording: t("omnichannel.history.why.negativeWording"),
        whySlaExceeded: t("omnichannel.history.why.slaExceeded"),
        whyAskedManager: t("omnichannel.history.why.askedManager"),
        whyMentionedRefund: t("omnichannel.history.why.mentionedRefund"),
        whyThreatenedCancellation: t("omnichannel.history.why.threatenedCancellation"),
        recommendAssignBilling: t("omnichannel.history.recommendations.assignBilling"),
        recommendEscalate: t("omnichannel.history.recommendations.escalate"),
        recommendOfferDiscount: t("omnichannel.history.recommendations.offerDiscount"),
        recommendReturnToAi: t("omnichannel.history.recommendations.returnToAi"),
        recommendCallCustomer: t("omnichannel.history.recommendations.callCustomer"),
        recommendCreateTicket: t("omnichannel.history.recommendations.createTicket"),
        recommendRequestSupervisor: t("omnichannel.history.recommendations.requestSupervisor"),
        healthHealthy: t("omnichannel.history.health.healthy"),
        healthWarning: t("omnichannel.history.health.warning"),
        healthCritical: t("omnichannel.history.health.critical"),
        journeyWhatsAppStarted: t("omnichannel.history.journey.whatsappStarted"),
        journeyCustomerCreated: t("omnichannel.history.journey.customerCreated"),
        journeyFirstBooking: t("omnichannel.history.journey.firstBooking"),
        journeyInvoice: t("omnichannel.history.journey.invoice"),
        journeyComplaint: t("omnichannel.history.journey.complaint"),
        journeyEscalation: t("omnichannel.history.journey.escalation"),
        journeyResolved: t("omnichannel.history.journey.resolved"),
        journeySurvey: t("omnichannel.history.journey.survey"),
      },
    }),
    [t],
  );
}

export function useIntelligenceSidebarLabels(): import("@/components/omnichannel/workspace-v2/conversation-intelligence-sidebar").ConversationIntelligenceSidebarLabels {
  const { t } = useTranslation("common");
  const sidebar = useWorkspaceSidebarLabels();
  return useMemo(
    () => ({
      title: t("omnichannel.intelligence.title"),
      collapseLabel: t("omnichannel.intelligence.collapse"),
      expandLabel: t("omnichannel.intelligence.expand"),
      emptyConversation: t("omnichannel.intelligence.emptyConversation"),
      tabs: {
        summary: t("omnichannel.intelligence.tabs.summary"),
        history: t("omnichannel.intelligence.tabs.history"),
        mood: t("omnichannel.intelligence.tabs.mood"),
        recommendation: t("omnichannel.intelligence.tabs.recommendation"),
        health: t("omnichannel.intelligence.tabs.health"),
        journey: t("omnichannel.intelligence.tabs.journey"),
        crm: t("omnichannel.intelligence.tabs.crm"),
      },
      crm: {
        title: t("omnichannel.intelligence.crm.title"),
        notLinkedTitle: t("omnichannel.intelligence.crm.notLinkedTitle"),
        notLinkedHint: t("omnichannel.intelligence.crm.notLinkedHint"),
        linkCustomer: t("omnichannel.intelligence.crm.linkCustomer"),
        createCustomer: t("omnichannel.intelligence.crm.createCustomer"),
        customerName: t("omnichannel.intelligence.crm.customerName"),
        company: t("omnichannel.intelligence.crm.company"),
        phone: t("omnichannel.intelligence.crm.phone"),
        email: t("omnichannel.intelligence.crm.email"),
        status: t("omnichannel.intelligence.crm.status"),
        vip: t("omnichannel.intelligence.crm.vip"),
        createdDate: t("omnichannel.intelligence.crm.createdDate"),
        lastActivity: t("omnichannel.intelligence.crm.lastActivity"),
        openTickets: t("omnichannel.intelligence.crm.openTickets"),
        totalOrders: t("omnichannel.intelligence.crm.totalOrders"),
        totalRevenue: t("omnichannel.intelligence.crm.totalRevenue"),
        yes: t("omnichannel.intelligence.crm.yes"),
        no: t("omnichannel.intelligence.crm.no"),
      },
      panel: sidebar.historyPanel,
      polish: {
        scoreTitle: t("omnichannel.intelligence.polish.scoreTitle"),
        scoreExcellent: t("omnichannel.intelligence.polish.scoreExcellent"),
        scoreGood: t("omnichannel.intelligence.polish.scoreGood"),
        scoreFair: t("omnichannel.intelligence.polish.scoreFair"),
        scorePoor: t("omnichannel.intelligence.polish.scorePoor"),
        trendTitle: t("omnichannel.intelligence.polish.trendTitle"),
        trendImproving: t("omnichannel.intelligence.polish.trendImproving"),
        trendStable: t("omnichannel.intelligence.polish.trendStable"),
        trendDeclining: t("omnichannel.intelligence.polish.trendDeclining"),
        recommendedNextAction: t("omnichannel.intelligence.polish.recommendedNextAction"),
        recommendReasonAssignBilling: t("omnichannel.intelligence.polish.recommendReasonAssignBilling"),
        recommendReasonEscalate: t("omnichannel.intelligence.polish.recommendReasonEscalate"),
        recommendReasonOfferDiscount: t("omnichannel.intelligence.polish.recommendReasonOfferDiscount"),
        recommendReasonReturnToAi: t("omnichannel.intelligence.polish.recommendReasonReturnToAi"),
        recommendReasonCallCustomer: t("omnichannel.intelligence.polish.recommendReasonCallCustomer"),
        recommendReasonCreateTicket: t("omnichannel.intelligence.polish.recommendReasonCreateTicket"),
        recommendReasonRequestSupervisor: t("omnichannel.intelligence.polish.recommendReasonRequestSupervisor"),
        overallHealth: t("omnichannel.intelligence.polish.overallHealth"),
        healthTickets: t("omnichannel.intelligence.polish.healthTickets"),
        healthAiMessages: t("omnichannel.intelligence.polish.healthAiMessages"),
        dateLastWeek: t("omnichannel.intelligence.polish.dateLastWeek"),
        eventReply: t("omnichannel.intelligence.polish.eventReply"),
        eventAiReply: t("omnichannel.intelligence.polish.eventAiReply"),
        eventInternalNote: t("omnichannel.intelligence.polish.eventInternalNote"),
        eventAssignment: t("omnichannel.intelligence.polish.eventAssignment"),
        eventEscalation: t("omnichannel.intelligence.polish.eventEscalation"),
        eventResolve: t("omnichannel.intelligence.polish.eventResolve"),
        eventClose: t("omnichannel.intelligence.polish.eventClose"),
        eventReopen: t("omnichannel.intelligence.polish.eventReopen"),
        eventTicket: t("omnichannel.intelligence.polish.eventTicket"),
        eventCustomerLinked: t("omnichannel.intelligence.polish.eventCustomerLinked"),
        eventTakeOver: t("omnichannel.intelligence.polish.eventTakeOver"),
        eventReturnToAi: t("omnichannel.intelligence.polish.eventReturnToAi"),
        eventWorkflow: t("omnichannel.intelligence.polish.eventWorkflow"),
        eventAutomation: t("omnichannel.intelligence.polish.eventAutomation"),
        eventDefault: t("omnichannel.intelligence.polish.eventDefault"),
      },
      v2: {
        satisfactionTitle: t("omnichannel.intelligence.v2.satisfactionTitle"),
        confidenceTitle: t("omnichannel.intelligence.v2.confidenceTitle"),
        analysisReasonTitle: t("omnichannel.intelligence.v2.analysisReasonTitle"),
        positiveSignals: t("omnichannel.intelligence.v2.positiveSignals"),
        negativeSignals: t("omnichannel.intelligence.v2.negativeSignals"),
        smartSummaryTitle: t("omnichannel.intelligence.v2.smartSummaryTitle"),
        summaryRequestType: t("omnichannel.intelligence.v2.summaryRequestType"),
        summaryWho: t("omnichannel.intelligence.v2.summaryWho"),
        summaryReason: t("omnichannel.intelligence.v2.summaryReason"),
        generalInquiry: t("omnichannel.intelligence.v2.generalInquiry"),
        latestCustomerMessage: t("omnichannel.intelligence.v2.latestCustomerMessage"),
        latestTeamReply: t("omnichannel.intelligence.v2.latestTeamReply"),
        summaryDone: t("omnichannel.intelligence.v2.summaryDone"),
        summaryNeeded: t("omnichannel.intelligence.v2.summaryNeeded"),
        summaryFollowUp: t("omnichannel.intelligence.v2.summaryFollowUp"),
        summaryLastAction: t("omnichannel.intelligence.v2.summaryLastAction"),
        summaryLastReply: t("omnichannel.intelligence.v2.summaryLastReply"),
        yes: t("omnichannel.intelligence.v2.yes"),
        no: t("omnichannel.intelligence.v2.no"),
        kpiDuration: t("omnichannel.intelligence.v2.kpiDuration"),
        kpiMessages: t("omnichannel.intelligence.v2.kpiMessages"),
        kpiFirstReply: t("omnichannel.intelligence.v2.kpiFirstReply"),
        kpiAiPercent: t("omnichannel.intelligence.v2.kpiAiPercent"),
        kpiHumanPercent: t("omnichannel.intelligence.v2.kpiHumanPercent"),
        kpiSatisfaction: t("omnichannel.intelligence.v2.kpiSatisfaction"),
        healthScoreTitle: t("omnichannel.intelligence.v2.healthScoreTitle"),
        healthMessageCount: t("omnichannel.intelligence.v2.healthMessageCount"),
        healthFirstReply: t("omnichannel.intelligence.v2.healthFirstReply"),
        healthLastReply: t("omnichannel.intelligence.v2.healthLastReply"),
        healthTransfers: t("omnichannel.intelligence.v2.healthTransfers"),
        healthHasTicket: t("omnichannel.intelligence.v2.healthHasTicket"),
        healthHasCrm: t("omnichannel.intelligence.v2.healthHasCrm"),
        healthHasNotes: t("omnichannel.intelligence.v2.healthHasNotes"),
        healthNewCustomer: t("omnichannel.intelligence.v2.healthNewCustomer"),
        healthVip: t("omnichannel.intelligence.v2.healthVip"),
        checklistTitle: t("omnichannel.intelligence.v2.checklistTitle"),
        checkShowPrices: t("omnichannel.intelligence.v2.checkShowPrices"),
        checkShowDiscounts: t("omnichannel.intelligence.v2.checkShowDiscounts"),
        checkSuggestAppointment: t("omnichannel.intelligence.v2.checkSuggestAppointment"),
        checkTransferSales: t("omnichannel.intelligence.v2.checkTransferSales"),
        checkCreateTicket: t("omnichannel.intelligence.v2.checkCreateTicket"),
        checkNeedsFollowUp: t("omnichannel.intelligence.v2.checkNeedsFollowUp"),
        journeyStarted: t("omnichannel.intelligence.v2.journeyStarted"),
        journeyAiReplied: t("omnichannel.intelligence.v2.journeyAiReplied"),
        journeyAgentJoined: t("omnichannel.intelligence.v2.journeyAgentJoined"),
        journeyTransferred: t("omnichannel.intelligence.v2.journeyTransferred"),
        journeyTicketCreated: t("omnichannel.intelligence.v2.journeyTicketCreated"),
        journeyResolved: t("omnichannel.intelligence.v2.journeyResolved"),
        journeyClosed: t("omnichannel.intelligence.v2.journeyClosed"),
        reasonPositiveWords: t("omnichannel.intelligence.v2.reasonPositiveWords"),
        reasonIssueResolved: t("omnichannel.intelligence.v2.reasonIssueResolved"),
        reasonFastReply: t("omnichannel.intelligence.v2.reasonFastReply"),
        reasonSlowReply: t("omnichannel.intelligence.v2.reasonSlowReply"),
        scoreExcellent: t("omnichannel.intelligence.polish.scoreExcellent"),
        scoreGood: t("omnichannel.intelligence.polish.scoreGood"),
        scoreFair: t("omnichannel.intelligence.polish.scoreFair"),
        scorePoor: t("omnichannel.intelligence.polish.scorePoor"),
      },
    }),
    [sidebar.historyPanel, t],
  );
}

export function useConversationViewLabels() {
  const { t } = useTranslation("common");
  return useMemo(
    () => ({
      selectConversation: t("omnichannel.selectConversation"),
      loading: t("status.loading"),
      unknownContact: t("omnichannel.unknownContact"),
      createCustomer: t("omnichannel.customer.createCustomer"),
      linkCustomer: t("omnichannel.customer.linkCustomer"),
      vip: t("omnichannel.customer.vip"),
      owner: t("omnichannel.customer.owner"),
      unassigned: t("omnichannel.customer.unassigned"),
      escalated: t("omnichannel.escalatedBadge"),
      status: t("omnichannel.header.status"),
      sla: t("omnichannel.header.sla"),
      language: t("omnichannel.header.language"),
      lastActivity: t("omnichannel.header.lastActivity"),
      assignedTo: t("omnichannel.header.assignedTo"),
      assignedAgent: t("omnichannel.header.assignedAgent"),
      aiEmployee: t("omnichannel.header.aiEmployee"),
      queue: t("omnichannel.header.queue"),
      escalationLevel: t("omnichannel.header.escalationLevel", { defaultValue: "Escalation" }),
      customerSince: t("omnichannel.header.customerSince", { defaultValue: "Customer since" }),
      priority: t("omnichannel.header.priority"),
      slaBreached: t("omnichannel.header.slaBreached"),
      noSla: t("omnichannel.header.noSla"),
      slaRemainingMinutes: (count: number) => t("omnichannel.header.slaRemainingMinutes", { count }),
      slaRemainingHours: (count: number) => t("omnichannel.header.slaRemainingHours", { count }),
      openProfile: t("omnichannel.header.openProfile"),
      resolve: t("omnichannel.actions.resolve"),
      reopen: t("omnichannel.actions.reopen"),
      reply: t("omnichannel.actions.reply"),
      assign: t("omnichannel.actions.assign"),
      transfer: t("omnichannel.actions.transfer"),
      takeOver: t("omnichannel.actions.takeOver"),
      statusAction: t("omnichannel.actions.status"),
      escalate: t("omnichannel.actions.escalate"),
      close: t("omnichannel.actions.close"),
      ai: t("omnichannel.actions.ai"),
      aiAssist: t("omnichannel.actions.aiAssist"),
      release: t("omnichannel.actions.release"),
      returnToAi: t("omnichannel.actions.returnToAi"),
      returnConversation: t("omnichannel.actions.returnConversation"),
      cancelEscalation: t("omnichannel.actions.cancelEscalation"),
      more: t("omnichannel.actions.more"),
      internalNote: t("omnichannel.composer.internalNote"),
      send: t("omnichannel.composer.send"),
      templates: t("omnichannel.composer.templates"),
      savedReplies: t("omnichannel.composer.savedReplies"),
      slashCommands: t("omnichannel.composer.slashCommands"),
      snippetCommands: t("omnichannel.composer.snippetCommands"),
      undoSend: t("omnichannel.composer.undoSend"),
      undoAction: t("omnichannel.composer.undoAction"),
      starMessage: t("omnichannel.experience.starMessage"),
      attachmentPreview: t("omnichannel.experience.attachmentPreview"),
      messageAttachments: {
        download: t("omnichannel.experience.attachmentDownload"),
        openFullscreen: t("omnichannel.experience.attachmentFullscreen"),
        closeFullscreen: t("omnichannel.experience.attachmentCloseFullscreen"),
      },
      composerTranslatePanel: {
        title: t("omnichannel.composer.translatePanel.title"),
        sourceLanguage: t("omnichannel.composer.translatePanel.sourceLanguage"),
        targetLanguage: t("omnichannel.composer.translatePanel.targetLanguage"),
        replace: t("omnichannel.composer.translatePanel.replace"),
        insertBelow: t("omnichannel.composer.translatePanel.insertBelow"),
        copy: t("omnichannel.composer.translatePanel.copy"),
        english: t("omnichannel.composer.translatePanel.english"),
        arabic: t("omnichannel.composer.translatePanel.arabic"),
        emptyDraft: t("omnichannel.composer.translatePanel.emptyDraft"),
      },
      composerMentionPanel: {
        agents: t("omnichannel.composer.mentionPanel.agents"),
        teams: t("omnichannel.composer.mentionPanel.teams"),
        online: t("omnichannel.composer.mentionPanel.online"),
      },
      smartTime: {
        justNow: t("omnichannel.experience.justNow"),
        minutesAgo: (count: number) => t("omnichannel.experience.minutesAgo", { count }),
        yesterday: t("omnichannel.experience.yesterday"),
      },
      transcriptSearch: {
        placeholder: t("omnichannel.experience.searchPlaceholder"),
        previous: t("omnichannel.experience.searchPrevious"),
        next: t("omnichannel.experience.searchNext"),
        clear: t("omnichannel.experience.searchClear"),
        bookmarks: t("omnichannel.experience.bookmarks"),
        noMatches: t("omnichannel.experience.noMatches"),
      },
      newMessages: t("omnichannel.experience.newMessages"),
      typingIndicator: {
        customer: t("omnichannel.experience.customerTyping"),
        agent: t("omnichannel.experience.agentTyping"),
        ai: t("omnichannel.experience.aiGenerating"),
      },
      presence: {
        online: t("omnichannel.experience.presenceOnline"),
        offline: t("omnichannel.experience.presenceOffline"),
        away: t("omnichannel.experience.presenceAway"),
        busy: t("omnichannel.experience.presenceBusy"),
        typing: t("omnichannel.experience.presenceTyping"),
        lastSeen: t("omnichannel.experience.lastSeen"),
      },
      conversationBookmarks: {
        pin: t("omnichannel.experience.pinConversation"),
        star: t("omnichannel.experience.starConversation"),
        markUnread: t("omnichannel.experience.markUnread"),
        follow: t("omnichannel.experience.followConversation"),
      },
      variables: t("omnichannel.composer.variables"),
      voicePlaceholder: t("omnichannel.composer.voicePlaceholder"),
      emoji: t("omnichannel.composer.emoji"),
      attachments: t("omnichannel.composer.attachments"),
      aiRewrite: t("omnichannel.composer.aiRewrite"),
      translate: t("omnichannel.composer.translate"),
      composerPlaceholder: t("omnichannel.composer.placeholder"),
      languageComposer: t("omnichannel.composer.language"),
      suggestedReplies: t("omnichannel.composer.suggestedReplies"),
      keyboardHint: t("omnichannel.composer.keyboardHint"),
      emptyTranscript: t("omnichannel.desk.noMessages"),
      emptyTranscriptHint: t("omnichannel.desk.noMessagesHint"),
      sessionEmptyDescription: t("omnichannel.desk.sessionEmptyDescription"),
      openInbox: t("omnichannel.desk.openInbox"),
      browseFilters: t("omnichannel.desk.browseFilters"),
      today: t("omnichannel.desk.today"),
      transcriptInternalNote: t("omnichannel.desk.transcriptInternalNote"),
      voiceLabel: t("omnichannel.desk.voice"),
      deliveryStatus: {
        pending: t("omnichannel.delivery.pending"),
        sent: t("omnichannel.delivery.sent"),
        delivered: t("omnichannel.delivery.delivered"),
        failed: t("omnichannel.delivery.failed"),
        read: t("omnichannel.delivery.read"),
        draft: t("omnichannel.delivery.draft"),
        preparing: t("omnichannel.delivery.preparing"),
        dispatching: t("omnichannel.delivery.dispatching"),
        pending_retry: t("omnichannel.delivery.pendingRetry"),
      },
      channelConnection: {
        connected: t("omnichannel.delivery.channelConnected"),
        error: t("omnichannel.delivery.channelError"),
        reconnect: t("omnichannel.delivery.reconnectChannel"),
        diagnostics: t("omnichannel.delivery.openChannelDiagnostics"),
      },
      supportAgent: t("omnichannel.header.supportAgent"),
      open: t("omnichannel.actions.open"),
      visitorLabel: t("omnichannel.visitorLabel"),
      mention: t("omnichannel.composer.mention"),
      composerDisabledReasons: {
        attachments: t("omnichannel.composer.disabled.attachments"),
        voice: t("omnichannel.composer.disabled.voice"),
        templates: t("omnichannel.composer.disabled.templates"),
        aiRewrite: t("omnichannel.composer.disabled.aiRewrite"),
        translate: t("omnichannel.composer.disabled.translate"),
        mention: t("omnichannel.composer.disabled.mention"),
        generic: t("omnichannel.composer.disabled.generic"),
      },
      comingSoon: t("omnichannel.composer.comingSoon"),
      comingSoonHint: t("omnichannel.composer.comingSoonHint"),
    }),
    [t],
  );
}

export function useWorkspaceNavLabels() {
  const { t } = useTranslation("common");
  return useMemo(
    () => ({
      inbox: t("omnichannel.workspace.nav.inbox"),
      mine: t("omnichannel.workspace.nav.mine"),
      assigned: t("omnichannel.workspace.nav.assigned"),
      escalated: t("omnichannel.workspace.nav.escalated"),
      waiting: t("omnichannel.workspace.nav.waiting"),
      closed: t("omnichannel.workspace.nav.closed"),
      ai: t("omnichannel.workspace.nav.ai"),
      archived: t("omnichannel.workspace.nav.archived"),
    }),
    [t],
  );
}

export function useWorkspaceChromeLabels() {
  const { t } = useTranslation("common");
  return useMemo(
    () => ({
      settings: t("omnichannel.workspace.settings"),
      notifications: t("omnichannel.workspace.notifications"),
      collapseCustomer: t("omnichannel.workspace.collapseCustomer"),
      expandCustomer: t("omnichannel.workspace.expandCustomer"),
      navAria: t("omnichannel.workspace.navAria"),
    }),
    [t],
  );
}

export function useAgentDeskLabels() {
  const { t } = useTranslation("common");
  return useMemo(
    () => ({
      subtitle: t("omnichannel.desk.subtitle"),
      filters: t("omnichannel.desk.filters"),
      closeFilters: t("omnichannel.desk.closeFilters"),
      closeQueue: t("omnichannel.desk.closeQueue"),
      conversationQueue: t("omnichannel.desk.conversationQueue"),
      inbox: t("omnichannel.desk.inbox"),
      close: t("omnichannel.desk.close"),
      openConversationList: t("omnichannel.desk.openConversationList"),
      queueNavigation: t("omnichannel.desk.queueNavigation"),
      sessionCommands: t("omnichannel.desk.sessionCommands"),
      customer360: t("omnichannel.desk.customer360"),
      closeCustomer360: t("omnichannel.desk.closeCustomer360"),
      adjustFiltersHint: t("omnichannel.desk.adjustFiltersHint"),
      notAvailable: t("omnichannel.desk.notAvailable"),
      unreadOverflow: t("omnichannel.desk.unreadOverflow"),
      backToConversation: t("omnichannel.navigation.backToConversation"),
      resizeQueue: t("omnichannel.desk.resizeQueue"),
      maximizeConversation: t("omnichannel.desk.maximizeConversation"),
      channelSection: t("omnichannel.filters.channel"),
      tagSection: t("omnichannel.filters.tag"),
      lifecycle: (state: string) =>
        t(`omnichannel.lifecycle.${state}`, {
          defaultValue: state.replace(/_/g, " ").toLowerCase(),
        }),
      channel: (key: string) =>
        t(`omnichannel.channels.${key}`, { defaultValue: key }),
      priority: (key: string) =>
        t(`dashboard.notifications.priority.${key}`, { defaultValue: key }),
      emptySecondary: {
        session: t("omnichannel.emptyStates.sessionSecondary"),
        queue: t("omnichannel.emptyStates.queueSecondary"),
        transcript: t("omnichannel.emptyStates.transcriptSecondary"),
        insight: t("omnichannel.emptyStates.insightSecondary"),
      },
      insightEmptyHint: t("omnichannel.sidebar.insightEmptyHint"),
    }),
    [t],
  );
}

const TAG_DEFINITIONS = [
  { id: "vip", labelKey: "omnichannel.tags.vip" },
  { id: "complaint", labelKey: "omnichannel.tags.complaint" },
  { id: "sales", labelKey: "omnichannel.tags.sales" },
  { id: "support", labelKey: "omnichannel.tags.support" },
] as const;

export function useConversationTagOptions(
  conversations: Array<{ source: { metadata: Record<string, unknown> } }>,
) {
  const { t } = useTranslation("common");
  return useMemo(
    () =>
      TAG_DEFINITIONS.map((tag) => ({
        id: tag.id,
        label: t(tag.labelKey),
        count: conversations.filter((conversation) => {
          const tags = conversation.source.metadata?.tags;
          if (!Array.isArray(tags)) return false;
          return tags.some((entry) => String(entry).toLowerCase() === tag.id);
        }).length,
      })),
    [conversations, t],
  );
}
