packages:
  - artifacts/*
  - lib/*
  - lib/integrations/*
  - scripts

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

autoInstallPeers: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver
