import {
  BarChart3,
  BookOpen,
  Bot,
  Eye,
  Mail,
  MessageSquare,
  Mic,
  Workflow,
  Zap,
} from "lucide-react";
import {
  PLATFORM_AI_CAPABILITY_ID,
  PLATFORM_AI_FEATURE_KEY,
} from "@workspace/platform-ai-provider";
import type { AiCapabilityDefinition } from "./ai-capability-catalog-schema";

export const AI_CAPABILITY_CATALOG: readonly AiCapabilityDefinition[] = [
  {
    id: PLATFORM_AI_CAPABILITY_ID.AI_CHAT,
    displayNameKey: "platformAi.admin.features.aiChat.name",
    descriptionKey: "platformAi.admin.features.aiChat.description",
    category: "core",
    icon: MessageSquare,
    availability: "live",
    backendFeatureKey: PLATFORM_AI_FEATURE_KEY.AI_CHAT,
    minimumPlan: "Basic",
    dependencies: [],
    defaultEnabled: true,
    experimental: false,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.EMAIL_ASSISTANT,
    displayNameKey: "platformAi.admin.features.emailAssistant.name",
    descriptionKey: "platformAi.admin.features.emailAssistant.description",
    category: "communication",
    icon: Mail,
    availability: "coming_soon",
    minimumPlan: "Pro",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT],
    defaultEnabled: false,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.WHATSAPP_ASSISTANT,
    displayNameKey: "platformAi.admin.features.whatsappAssistant.name",
    descriptionKey: "platformAi.admin.features.whatsappAssistant.description",
    category: "communication",
    icon: MessageSquare,
    availability: "coming_soon",
    minimumPlan: "Pro",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT],
    defaultEnabled: false,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.KNOWLEDGE_BASE,
    displayNameKey: "platformAi.admin.features.knowledgeBase.name",
    descriptionKey: "platformAi.admin.features.knowledgeBase.description",
    category: "intelligence",
    icon: BookOpen,
    availability: "live",
    backendFeatureKey: PLATFORM_AI_FEATURE_KEY.KNOWLEDGE,
    minimumPlan: "Pro",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT],
    defaultEnabled: true,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.AI_ANALYTICS,
    displayNameKey: "platformAi.admin.features.aiAnalytics.name",
    descriptionKey: "platformAi.admin.features.aiAnalytics.description",
    category: "intelligence",
    icon: BarChart3,
    availability: "coming_soon",
    minimumPlan: "Pro",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT],
    defaultEnabled: false,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.WORKFLOW_AI,
    displayNameKey: "platformAi.admin.features.workflowAi.name",
    descriptionKey: "platformAi.admin.features.workflowAi.description",
    category: "advanced",
    icon: Workflow,
    availability: "coming_soon",
    minimumPlan: "Pro",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT],
    defaultEnabled: false,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.AI_AGENTS,
    displayNameKey: "platformAi.admin.features.aiAgents.name",
    descriptionKey: "platformAi.admin.features.aiAgents.description",
    category: "advanced",
    icon: Bot,
    availability: "coming_soon",
    minimumPlan: "Enterprise",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT, PLATFORM_AI_CAPABILITY_ID.WORKFLOW_AI],
    defaultEnabled: false,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.VOICE_AI,
    displayNameKey: "platformAi.admin.features.voiceAi.name",
    descriptionKey: "platformAi.admin.features.voiceAi.description",
    category: "advanced",
    icon: Mic,
    availability: "coming_soon",
    minimumPlan: "Enterprise",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT],
    defaultEnabled: false,
    experimental: true,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.VISION_AI,
    displayNameKey: "platformAi.admin.features.visionAi.name",
    descriptionKey: "platformAi.admin.features.visionAi.description",
    category: "advanced",
    icon: Eye,
    availability: "coming_soon",
    minimumPlan: "Enterprise",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT],
    defaultEnabled: false,
    experimental: true,
    visible: true,
  },
  {
    id: PLATFORM_AI_CAPABILITY_ID.AI_AUTOMATION,
    displayNameKey: "platformAi.admin.features.aiAutomation.name",
    descriptionKey: "platformAi.admin.features.aiAutomation.description",
    category: "advanced",
    icon: Zap,
    availability: "coming_soon",
    minimumPlan: "Pro",
    dependencies: [PLATFORM_AI_CAPABILITY_ID.AI_CHAT, PLATFORM_AI_CAPABILITY_ID.WORKFLOW_AI],
    defaultEnabled: false,
    visible: true,
  },
] as const;

export function getAiCapabilityById(id: string): AiCapabilityDefinition | undefined {
  return AI_CAPABILITY_CATALOG.find((capability) => capability.id === id);
}
