import type { OperationsCustomer360WorkspaceData } from "../types/customer360-panel-types.js";

export type EmptyCustomer360Workspace = OperationsCustomer360WorkspaceData & { isEmpty: true };

/** Empty Customer360 workspace when no customer is selected — no mock entities. */
export function buildEmptyCustomer360Workspace(): EmptyCustomer360Workspace {
  return {
    isEmpty: true,
    customer: {
      id: "",
      name: "",
      email: "",
      phone: "",
      company: "",
      address: "",
      birthday: "",
      tags: [],
      healthScore: 0,
      avatarColor: "#64748b",
    },
    lead: {
      id: "",
      source: "",
      campaign: "",
      owner: "",
      score: 0,
      customFields: {},
      convertedAt: null,
    },
    todaysOperation: {
      id: "",
      reference: "",
      service: "",
      status: "",
      assignedEmployee: "",
      branch: "",
      room: "",
      durationMinutes: 0,
      scheduledAt: "",
      arrivalAt: null,
      checkInAt: null,
      checkOutAt: null,
      countdownMinutes: 0,
      paymentStatus: "",
      paymentAmountCents: 0,
    },
    summary: {
      photoUrl: null,
      isVip: false,
      customerSince: "",
      lastVisit: "",
      totalVisits: 0,
      totalRevenueCents: 0,
      lifetimeValueCents: 0,
      preferredEmployee: "",
      preferredTime: "",
      preferredService: "",
      riskLevel: "low",
      satisfaction: 0,
      aiHealthScore: 0,
    },
    communications: [],
    timeline: [],
    notesExtended: [],
    aiActions: [],
    bookings: [],
    invoices: [],
    payments: [],
    activities: [],
    files: [],
    tasks: [],
    notes: [],
    aiInsights: [],
    outstandingBalanceCents: 0,
    currentStatus: "",
    currentPaymentStatus: "",
    assignedResource: "",
    priority: "",
  };
}
