import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BookOpen,
  Bot,
  Building2,
  CalendarDays,
  Coins,
  CreditCard,
  FileText,
  Flag,
  LayoutDashboard,
  Mail,
  MessageSquare,
  Package,
  Plug,
  Radio,
  Repeat,
  ScrollText,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Ticket,
  UserCog,
  Users,
  Workflow,
  Wrench,
} from "lucide-react";

export const PERMISSION_MODULE_ICONS: Record<string, LucideIcon> = {
  email: Mail,
  channels: Radio,
  whatsapp: MessageSquare,
  conversations: MessageSquare,
  handoff: Repeat,
  aiAssistant: Bot,
  aiChat: Sparkles,
  knowledge: BookOpen,
  prompts: ScrollText,
  agents: Bot,
  skills: Sparkles,
  automation: Workflow,
  aiAnalytics: Activity,
  aiPlatform: Sparkles,
  governance: ShieldCheck,
  operations: Wrench,
  configuration: Settings,
  featureFlags: Flag,
  customers: Users,
  leads: Users,
  opportunities: FileText,
  tickets: Ticket,
  products: Package,
  quotes: FileText,
  bookings: CalendarDays,
  scheduling: CalendarDays,
  invoices: CreditCard,
  company: Building2,
  organization: Building2,
  users: Users,
  roles: ShieldCheck,
  settings: Settings,
  audit: FileText,
  companies: Building2,
  workspace: Building2,
  dashboard: LayoutDashboard,
  billing: Coins,
  reports: FileText,
  executive: Activity,
  licenses: ScrollText,
  tasks: FileText,
  marketplace: Store,
  integrations: Plug,
};

export function permissionModuleIcon(moduleId: string): LucideIcon {
  return PERMISSION_MODULE_ICONS[moduleId] ?? Sparkles;
}
