import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import emailRouter from "./email.js";
import whatsappRouter from "./whatsapp.js";
import instagramRouter from "./instagram.js";
import messengerRouter from "./messenger.js";
import smsRouter from "./sms.js";
import emailChannelRouter from "./email-channel.js";
import emailMailboxProviderRouter from "./email-mailbox-provider.js";
import emailAiDraftRouter from "./email-ai-draft.js";
import emailMessageTranslateRouter from "./email-message-translate.js";
import emailComposeSessionRouter from "./email-compose-session.js";
import emailWorkspaceChannelRouter from "./email-workspace-channel.js";
import omnichannelRouter from "./omnichannel.js";
import v1Router from "./v1/index.js";
import internalBillingRouter from "./internal-billing.js";
import billingSaasRouter from "./billing-saas.js";
import platformAiRouter from "./platform-ai.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(emailRouter);
router.use(whatsappRouter);
router.use(instagramRouter);
router.use(messengerRouter);
router.use(smsRouter);
router.use(emailChannelRouter);
router.use(emailMailboxProviderRouter);
router.use(emailAiDraftRouter);
router.use(emailMessageTranslateRouter);
router.use(emailComposeSessionRouter);
router.use(emailWorkspaceChannelRouter);
router.use(omnichannelRouter);
router.use("/platform-ai", platformAiRouter);
router.use("/v1", v1Router);
router.use("/internal/billing", internalBillingRouter);
router.use("/billing/saas", billingSaasRouter);

export default router;
