/** Presentation labels for customer insight / workspace panels. */
import type { OutboundDeliveryPhase } from "@/lib/omnichannel/services/outbound-delivery";
import type { MessageStatus } from "@workspace/ai-conversation";
import type { ConversationHistoryPanelLabels } from "@/components/omnichannel/workspace-v2/conversation-history-panel";
export type WorkspaceSidebarLabels = {
  conversation: string;
  overview: string;
  customer: string;
  aiSummary: string;
  crm: string;
  assignment: string;
  properties: string;
  timeline: string;
  internalNotes: string;
  internalNotesPanel: {
    empty: string;
    author: string;
    edit: string;
    delete: string;
    save: string;
    cancel: string;
    deleteConfirm: string;
    editedBy: string;
    editedAt: string;
    versionHistory: string;
    conversationScoped: string;
  };
  recentActivity: string;
  empty: string;
  summary: string;
  intent: string;
  sentiment: string;
  priority: string;
  suggestedReply: string;
  confidence: string;
  assignTo: string;
  currentOwner: string;
  escalationHistory: string;
  returnConversation: string;
  lifetimeValue: string;
  bookings: string;
  linkCustomer: string;
  crmTabs: {
    customer: string;
    orders: string;
    invoices: string;
    tickets: string;
    activities: string;
    timeline: string;
  };
  targetTypes: {
    user: string;
    team: string;
    department: string;
    ai_employee: string;
    queue: string;
  };
  historyPanel: ConversationHistoryPanelLabels;
  timelinePanel: {
    today: string;
    yesterday: string;
    lastWeek: string;
    assigned: string;
    assignedToTeam: string;
    assignedToQueue: string;
    assignedToAi: string;
    tookOver: string;
    returnedToAi: string;
    escalated: string;
    returnedFromEscalation: string;
    cancelledEscalation: string;
    resolved: string;
    closed: string;
    reopened: string;
    internalNoteAdded: string;
    internalNoteEdited: string;
    internalNoteDeleted: string;
    customerLinked: string;
    statusChanged: string;
    message: string;
    filterAll: string;
    filterAssignments: string;
    filterEscalations: string;
    filterInternalNotes: string;
    filterAi: string;
    filterStatusChanges: string;
    badgeAssignment: string;
    badgeEscalation: string;
    badgeInternalNote: string;
    badgeAi: string;
    badgeStatus: string;
    badgeCustomer: string;
    badgeMessage: string;
    badgeUpdate: string;
    searchPlaceholder: string;
    empty: string;
    openAssignee: string;
    openCustomer360: string;
  };
};

export type ConversationViewLabels = {
  selectConversation: string;
  loading: string;
  unknownContact: string;
  createCustomer: string;
  linkCustomer: string;
  vip: string;
  owner: string;
  unassigned: string;
  escalated: string;
  status: string;
  sla: string;
  language: string;
  lastActivity: string;
  assignedTo: string;
  queue: string;
  escalationLevel: string;
  customerSince: string;
  priority: string;
  resolve: string;
  reopen: string;
  reply: string;
  assign: string;
  transfer: string;
  takeOver: string;
  statusAction: string;
  escalate: string;
  close: string;
  ai: string;
  aiAssist: string;
  release: string;
  returnToAi: string;
  returnConversation: string;
  cancelEscalation: string;
  more: string;
  internalNote: string;
  send: string;
  templates: string;
  savedReplies: string;
  slashCommands: string;
  variables: string;
  voicePlaceholder: string;
  emoji: string;
  attachments: string;
  aiRewrite: string;
  translate: string;
  composerPlaceholder: string;
  languageComposer: string;
  suggestedReplies: string;
  keyboardHint: string;
  emptyTranscript: string;
  emptyTranscriptHint: string;
  sessionEmptyDescription: string;
  openInbox: string;
  browseFilters: string;
  today: string;
  transcriptInternalNote: string;
  voiceLabel: string;
  visitorLabel: string;
  deliveryStatus: Partial<Record<MessageStatus | OutboundDeliveryPhase, string>>;
  channelConnection: {
    connected: string;
    error: string;
    reconnect: string;
    diagnostics: string;
  };
  smartTime: {
    justNow: string;
    minutesAgo: (count: number) => string;
    yesterday: string;
  };
  transcriptSearch: {
    placeholder: string;
    previous: string;
    next: string;
    clear: string;
    bookmarks: string;
    noMatches: string;
  };
  newMessages: string;
  typingIndicator: {
    customer: string;
    agent: string;
    ai: string;
  };
  presence: {
    online: string;
    offline: string;
    away: string;
    busy: string;
    typing: string;
    lastSeen: string;
  };
  starMessage: string;
  snippetCommands: string;
  undoSend: string;
  undoAction: string;
  attachmentPreview: string;
  messageAttachments: {
    download: string;
    openFullscreen: string;
    closeFullscreen: string;
  };
  composerTranslatePanel: {
    title: string;
    sourceLanguage: string;
    targetLanguage: string;
    replace: string;
    insertBelow: string;
    copy: string;
    english: string;
    arabic: string;
    emptyDraft: string;
  };
  composerMentionPanel: {
    agents: string;
    teams: string;
    online: string;
  };
  conversationBookmarks: {
    pin: string;
    star: string;
    markUnread: string;
    follow: string;
  };
  supportAgent: string;
  mention: string;
  assignedAgent: string;
  aiEmployee: string;
  slaBreached: string;
  noSla: string;
  slaRemainingMinutes: (count: number) => string;
  slaRemainingHours: (count: number) => string;
  openProfile: string;
  composerDisabledReasons: Partial<
    Record<
      "attachments" | "voice" | "templates" | "savedReplies" | "aiRewrite" | "translate" | "mention",
      string
    >
  > & { generic: string };
  comingSoon: string;
  comingSoonHint: string;
};

export type AgentDeskLabels = {
  subtitle: string;
  filters: string;
  closeFilters: string;
  closeQueue: string;
  conversationQueue: string;
  inbox: string;
  close: string;
  openConversationList: string;
  queueNavigation: string;
  sessionCommands: string;
  customer360: string;
  closeCustomer360: string;
  adjustFiltersHint: string;
  notAvailable: string;
  unreadOverflow: string;
  backToConversation: string;
  channelSection: string;
  tagSection: string;
  resizeQueue: string;
  maximizeConversation: string;
  lifecycle: (state: string) => string;
  channel: (key: string) => string;
  priority: (key: string) => string;
  emptySecondary: {
    session: string;
    queue: string;
    transcript: string;
    insight: string;
  };
  insightEmptyHint: string;
};
