import type { WorkflowDefinition } from "../../../workflow/types.js";

/**
 * Clinic patient journey — first industry pack on the Enterprise Workflow Engine.
 * Seeded pack (not runtime-hardcoded policy). Registered via WorkflowRegistry.
 */
export const WORKFLOW_PACK_CLINIC: WorkflowDefinition = {
  id: "clinic_patient_journey",
  templateKey: "clinic",
  labelKey: "universalOperations.workflows.clinic.label",
  roleAliases: {
    receptionist: "reception",
    nurse: "nurse",
    doctor: "doctor",
    cashier: "accountant",
    manager: "manager",
    reception: "reception",
    accountant: "accountant",
  },
  states: [
    { id: "st_waiting", internalName: "waiting", displayName: "Waiting", active: false },
    { id: "st_waiting", internalName: "pending", displayName: "Waiting", active: false },
    { id: "st_waiting", internalName: "booked", displayName: "Waiting", active: false },
    { id: "st_confirmed", internalName: "confirmed", displayName: "Confirmed", active: false },
    { id: "st_checked_in", internalName: "checked_in", displayName: "Checked In", active: true },
    { id: "st_with_nurse", internalName: "with_nurse", displayName: "With Nurse", active: true },
    { id: "st_with_doctor", internalName: "in_progress", displayName: "With Doctor", active: true },
    { id: "st_with_doctor", internalName: "with_doctor", displayName: "With Doctor", active: true },
    { id: "st_completed", internalName: "completed", displayName: "Completed" },
    { id: "st_archived", internalName: "archived", displayName: "Archived", terminal: true },
    { id: "st_archived", internalName: "cancelled", displayName: "Cancelled", terminal: true },
    { id: "st_archived", internalName: "no_show", displayName: "No Show", terminal: true },
    { id: "st_waiting", internalName: "rescheduled", displayName: "Rescheduled", active: false },
  ],
  stages: [
    {
      id: "waiting",
      labelKey: "universalOperations.workspace.workflow.waiting",
      statusInternalNames: ["booked", "waiting", "confirmed", "pending"],
      sortOrder: 0,
    },
    {
      id: "checked_in",
      labelKey: "universalOperations.workspace.workflow.checkedIn",
      statusInternalNames: ["checked_in"],
      sortOrder: 1,
    },
    {
      id: "with_nurse",
      labelKey: "universalOperations.workspace.workflow.withNurse",
      statusInternalNames: ["with_nurse"],
      sortOrder: 2,
    },
    {
      id: "with_doctor",
      labelKey: "universalOperations.workspace.workflow.withDoctor",
      statusInternalNames: ["in_progress", "with_doctor"],
      sortOrder: 3,
    },
    {
      id: "completed",
      labelKey: "universalOperations.workspace.workflow.completed",
      statusInternalNames: ["completed"],
      sortOrder: 4,
    },
    {
      id: "archived",
      labelKey: "universalOperations.workspace.workflow.archived",
      statusInternalNames: ["archived", "cancelled", "no_show"],
      sortOrder: 5,
    },
  ],
  kpiBuckets: {
    waiting: ["waiting", "booked", "confirmed", "pending"],
    in_progress: ["checked_in", "with_nurse", "in_progress", "with_doctor"],
    completed: ["completed"],
  },
  completionRules: {
    completedStates: ["completed"],
    archivedStates: ["archived", "cancelled", "no_show"],
    terminalStates: ["archived", "cancelled", "no_show"],
  },
  transitions: [
    // Domain-only edges (no Action Registry binding)
    {
      id: "clinic.confirm_booking",
      from: ["pending"],
      to: "confirmed",
      requiredPermissions: ["booking.write"],
      timelineEvent: {
        type: "booking_confirmed",
        labelKey: "universalOperations.timeline.events.bookingConfirmed",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.reschedule_from_pending",
      from: ["pending", "confirmed"],
      to: "rescheduled",
      requiredPermissions: ["booking.write"],
      timelineEvent: {
        type: "booking_rescheduled",
        labelKey: "universalOperations.timeline.events.bookingRescheduled",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.check_in",
      from: ["pending", "confirmed", "waiting", "booked"],
      to: "checked_in",
      actionId: "appointments.check_in",
      requiredPermissions: ["operations.write", "operations.queue.checkin"],
      actorRoles: ["reception", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.checkInTitle",
        descriptionKey: "universalOperations.actions.confirm.checkInDescription",
      },
      timelineEvent: {
        type: "patient_checked_in",
        labelKey: "universalOperations.timeline.events.patientCheckedIn",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.collect_payment",
      from: ["checked_in"],
      actionId: "billing.collect_payment",
      requiredPermissions: ["invoices.create", "operations.write"],
      actorRoles: ["reception", "accountant", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.collectTitle",
        descriptionKey: "universalOperations.actions.confirm.collectDescription",
      },
      timelineEvent: {
        type: "payment_collected",
        labelKey: "universalOperations.timeline.events.paymentCollected",
      },
      realtimeRefresh: true,
      paymentStatuses: ["unpaid", "pending", "partial"],
    },
    {
      id: "clinic.send_to_nurse",
      from: ["checked_in"],
      to: "with_nurse",
      actionId: "appointments.send_to_nurse",
      requiredPermissions: ["operations.write"],
      actorRoles: ["reception", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.sendToNurseTitle",
        descriptionKey: "universalOperations.actions.confirm.sendToNurseDescription",
      },
      timelineEvent: {
        type: "patient_sent_to_nurse",
        labelKey: "universalOperations.timeline.events.patientSentToNurse",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.complete_triage",
      from: ["with_nurse"],
      actionId: "appointments.complete_triage",
      requiredPermissions: ["operations.write"],
      actorRoles: ["nurse", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.completeTriageTitle",
        descriptionKey: "universalOperations.actions.confirm.completeTriageDescription",
      },
      timelineEvent: {
        type: "triage_completed",
        labelKey: "universalOperations.timeline.events.triageCompleted",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.send_to_doctor",
      from: ["with_nurse"],
      to: "in_progress",
      actionId: "appointments.send_to_doctor",
      requiredPermissions: ["operations.write"],
      actorRoles: ["nurse", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.sendToDoctorTitle",
        descriptionKey: "universalOperations.actions.confirm.sendToDoctorDescription",
      },
      timelineEvent: {
        type: "patient_sent_to_doctor",
        labelKey: "universalOperations.timeline.events.patientSentToDoctor",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.complete_visit",
      from: ["in_progress", "with_doctor"],
      to: "completed",
      actionId: "appointments.complete_visit",
      requiredPermissions: ["operations.write", "operations.queue.complete"],
      actorRoles: ["doctor", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.completeTitle",
        descriptionKey: "universalOperations.actions.confirm.completeDescription",
      },
      timelineEvent: {
        type: "visit_completed",
        labelKey: "universalOperations.timeline.events.visitCompleted",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.generate_invoice",
      from: ["completed"],
      actionId: "billing.generate_invoice",
      requiredPermissions: ["invoices.create", "operations.write"],
      actorRoles: ["accountant", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.invoiceTitle",
        descriptionKey: "universalOperations.actions.confirm.invoiceDescription",
      },
      timelineEvent: {
        type: "invoice_generated",
        labelKey: "universalOperations.timeline.events.invoiceGenerated",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.archive",
      from: ["completed"],
      to: "archived",
      actionId: "appointments.archive",
      requiredPermissions: ["operations.write"],
      actorRoles: ["reception", "accountant", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.archiveTitle",
        descriptionKey: "universalOperations.actions.confirm.archiveDescription",
      },
      timelineEvent: {
        type: "operation_archived",
        labelKey: "universalOperations.timeline.events.operationArchived",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.mark_no_show",
      from: ["pending", "confirmed", "waiting", "booked", "checked_in"],
      to: "no_show",
      actionId: "appointments.mark_no_show",
      requiredPermissions: ["operations.write"],
      actorRoles: ["reception", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.noShowTitle",
        descriptionKey: "universalOperations.actions.confirm.noShowDescription",
      },
      timelineEvent: {
        type: "patient_no_show",
        labelKey: "universalOperations.timeline.events.patientNoShow",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.cancel",
      from: ["pending", "confirmed", "waiting", "booked", "checked_in"],
      to: "cancelled",
      actionId: "appointments.cancel",
      requiredPermissions: ["booking.write", "bookings.delete"],
      actorRoles: ["reception", "manager"],
      confirmation: {
        titleKey: "universalOperations.actions.confirm.cancelTitle",
        descriptionKey: "universalOperations.actions.confirm.cancelDescription",
      },
      timelineEvent: {
        type: "booking_cancelled",
        labelKey: "universalOperations.timeline.events.bookingCancelled",
      },
      realtimeRefresh: true,
    },
    // Domain-only mid-journey exits (validity graph; not shown in Action Menu)
    {
      id: "clinic.cancel_mid",
      from: ["with_nurse", "in_progress", "with_doctor"],
      to: "cancelled",
      requiredPermissions: ["booking.write"],
      timelineEvent: {
        type: "booking_cancelled",
        labelKey: "universalOperations.timeline.events.bookingCancelled",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.no_show_mid",
      from: ["with_nurse"],
      to: "no_show",
      requiredPermissions: ["operations.write"],
      timelineEvent: {
        type: "patient_no_show",
        labelKey: "universalOperations.timeline.events.patientNoShow",
      },
      realtimeRefresh: true,
    },
    {
      id: "clinic.open",
      from: [
        "pending",
        "confirmed",
        "waiting",
        "booked",
        "checked_in",
        "with_nurse",
        "in_progress",
        "with_doctor",
        "completed",
        "archived",
        "cancelled",
        "no_show",
      ],
      actionId: "crm.open_customer360",
      requiredPermissions: [],
      actorRoles: ["reception", "nurse", "doctor", "accountant", "manager"],
      timelineEvent: {
        type: "operation_opened",
        labelKey: "universalOperations.timeline.events.operationOpened",
      },
      realtimeRefresh: false,
    },
  ],
};
